# Generated by Django 4.0.6 on 2022-07-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='publid_username',
            new_name='public_username',
        ),
    ]
