# Generated by Django 4.0.6 on 2022-08-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_poster_post_creator_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='commentator',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='poster',
        ),
    ]
