# Generated by Django 4.0.6 on 2022-08-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_creator_comment_commentator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='user',
        ),
    ]
