# Generated by Django 4.1 on 2022-08-31 06:12

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_account_poster_picture_account_profile_picture_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='poster_picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/poster_picture/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/profile_picture/'),
        ),
    ]
